WITH ProjectCounts AS (
    SELECT c.NAME AS CLIENT_NAME, COUNT(p.ID) AS PROJECT_COUNT
    FROM client c
    LEFT JOIN project p ON c.ID = p.CLIENT_ID
    GROUP BY c.NAME
)
SELECT CLIENT_NAME, PROJECT_COUNT
FROM ProjectCounts
WHERE PROJECT_COUNT = (SELECT MAX(PROJECT_COUNT) FROM ProjectCounts);